// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// getPartitionIdsAndOffsets
List getPartitionIdsAndOffsets(List indices, NumericMatrix psizes, NumericVector nparts);
RcppExport SEXP ddR_getPartitionIdsAndOffsets(SEXP indicesSEXP, SEXP psizesSEXP, SEXP npartsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type indices(indicesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type psizes(psizesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nparts(npartsSEXP);
    __result = Rcpp::wrap(getPartitionIdsAndOffsets(indices, psizes, nparts));
    return __result;
END_RCPP
}
