# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Gets the internal set of partitions, and offsets within each
#' partition, of a set 1d or 2d-subset indices for a distributed
#' object
#'
#' It returns a list of 3 elements, where the first element is a list
#' of partitions, the second is a list of row indices, and third a
#' a list of column indices.
#'
#' Note: This is an internal helper function of ddR.
#'
#' @param indices A sorted list of sorted vectors, where the first element
#' are the row indices, and the second (if 2d), column indices.
#' @param psizes Partition-sizes matrix of the distributed object.
#' @param nparts nparts vector of the distributed object.
getPartitionIdsAndOffsets <- function(indices, psizes, nparts) {
    .Call('ddR_getPartitionIdsAndOffsets', PACKAGE = 'ddR', indices, psizes, nparts)
}

